### ISSUE TITLE
won't download

### ISSUE THREAD

**Issue by pizzapiepizzapie** [yanncam/exe2powershell#2]
whenever I try to download this, it just says virus detected or couldn't download.

**Comment by yanncam** [comment]
Hello,

It is indeed possible that some antivirus now consider exe2powershell as a hack tool.

Browsers, such as Chrome, can therefore prevent its download. In which case you can go through Firefox or a simple wget for example.

Otherwise, a recompilation of the tool via its source code is also possible, if you want to modify its signature to avoid antiviral detection, or put an antiviral exception during use.

Sincerely,
